name: google_maps_webservice
description: Google Maps Web Services [API](https://developers.google.com/maps/web-services)
version: 0.0.20-nullsafety.1
homepage: https://github.com/lejard-h/google_maps_webservice

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  http: ^1.0.0
  meta: ^1.9.1
  json_annotation: ^4.8.1

dev_dependencies:
  test: ^1.24.3
  lint: ^2.1.2
  build_runner: ^2.4.5
  json_serializable: ^6.7.0
